### PR TITLE
fix: link cannot be resolved #89

### LINKED ISSUE #89: The link cannot be resolved when the hostname is not included
example:
```xml
<channel>
  <link>/</link>
  <language>en</language>
  <atom:link href="/index.xml" rel="self" type="application/rss+xml" />
  <item>
    <link>/posts/2023/06/piem/</link>
	<guid>/posts/2023/06/piem/</guid>
  </item>
</channel>
```
When the link is in the above format, it will be resolved as null:

```json
{
  "link": null,
  "language": "en",
  "atom:link": {
    "@_href": "/index.xml",
    "@_rel": "self",
    "@_type": "application/rss+xml"
  },
  "item": [
    {
      "link": null,
      "guid": "/posts/2023/06/piem/"
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by kahosan**
fix: #89

### CODE REVIEW

**Comment by ndaidong** [comment]
@kahosan thank you for your contribution.

What's you committed are good in logic. However there is some issues with coding convention need to get fixex.
Also, I have other ideas for your code:

1, The variable named `hostname` is not very suitable

At least in the context of URL object in JavaScript, where `hostname` usually does not contain protocol. 
In our case, it should be called `baseUrl` or something like that, to avoid confusion.

Screenshot from 2023-06-14 09-03-47


2, In the `extract()` method, parsing the hostname/baseUrl from feed url may leads to problem.

But sometimes the feed url may be different from the actual RSS resource. For example the feed urls from feedblitz, or feedburner. That's when the logic fails.

Let's try the following feeds:

- https://feeds.feedburner.com/MachineLearningMastery
- https://feeds.feedblitz.com/baeldung/cs&x=1

3, In the `extractFromJson()` and `extractFromXml()` methods, you pass hostname/baseUrl via the third parameter, which is not the best way,

With 2 and 3, I recommend to use the parameter `parserOptions` for all methods, to keep thing simple and consistent.

For example:

```js
extract('https://feeds.feedburner.com/MachineLearningMastery', {
  baseUrl: 'https://machinelearningmastery.com/',
})
```

**Comment by ndaidong** [comment]
> max-lines

yes, you can increase that number in the eslint config file.

**Comment by kahosan** [comment]
@ndaidong Should we let users fill in the baseUrl themselves?

**Comment by ndaidong** [comment]
> @ndaidong Should we let users fill in the baseUrl themselves?

yes, I think so. We only use this when encountering non-standard feeds.

**Comment by ndaidong** [comment]
@kahosan I've released v6.2.3 with your latest updates. Thank you.

**Pull request merged**
